title: "VISITORS OFFLINE"
description: "EXPOSING THE ALIEN TRUTH SINCE 1996"
url: "https://visitorsradio.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Line breaks
markdown: kramdown
kramdown:
  hard_wrap: true
