title: "VISITORS OFFLINE"
description: "EXPOSING THE ALIEN TRUTH SINCE 1996"
url: "https://visitorsradio.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
